// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-8N0ere7vRMUwKlVaLPg-7fuevI_VkWg',
    appId: '1:965019785692:web:ccdf34bc3b855b37ae5719',
    messagingSenderId: '965019785692',
    projectId: 'devildex-c15a3',
    authDomain: 'devildex-c15a3.firebaseapp.com',
    storageBucket: 'devildex-c15a3.firebasestorage.app',
    measurementId: 'G-N3981CMGFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdrX0lSpiYGZr64qv1S7MNy8n5xvVSsNo',
    appId: '1:965019785692:android:8a181ebbbbb6aea8ae5719',
    messagingSenderId: '965019785692',
    projectId: 'devildex-c15a3',
    storageBucket: 'devildex-c15a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF0PTDWPScgAI0X715WDqJNMkf87xmCvU',
    appId: '1:965019785692:ios:fdf1d4ea0dedd8a9ae5719',
    messagingSenderId: '965019785692',
    projectId: 'devildex-c15a3',
    storageBucket: 'devildex-c15a3.firebasestorage.app',
    iosBundleId: 'com.example.devilFruitdex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF0PTDWPScgAI0X715WDqJNMkf87xmCvU',
    appId: '1:965019785692:ios:fdf1d4ea0dedd8a9ae5719',
    messagingSenderId: '965019785692',
    projectId: 'devildex-c15a3',
    storageBucket: 'devildex-c15a3.firebasestorage.app',
    iosBundleId: 'com.example.devilFruitdex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-8N0ere7vRMUwKlVaLPg-7fuevI_VkWg',
    appId: '1:965019785692:web:cb55269f815f2c7eae5719',
    messagingSenderId: '965019785692',
    projectId: 'devildex-c15a3',
    authDomain: 'devildex-c15a3.firebaseapp.com',
    storageBucket: 'devildex-c15a3.firebasestorage.app',
    measurementId: 'G-HGXG2CTVZY',
  );
}
